name: "Set up config file for a run"
author: Luke Swanson
description: "Given a set of appropriate inputs, this action prepares the monitor app for deploy."
branding:
  icon: 'clipboard'
  color: 'blue'
inputs:
  python_path:
    description: "Path to python on the target server"
    required: true

runs:
  using: "composite"
  steps:
    # - name: Set up config
    #   run: cp src/config.php.template src/config.php 
    #   shell: bash
    - name: Set DB hostname
      run: sed -i 's@/path/to/python@${{ inputs.python_path }}@g' src/monitor_app.py
      shell: bash
